services:
  deno:
    build: .
    container_name: kepler-bot-prod
    restart: always
    environment:
      TOKEN: ${TOKEN}
      SUPABASE_URL: ${SUPABASE_URL}
      SUPABASE_SERVICE_ROLE_KEY: ${SUPABASE_SERVICE_ROLE_KEY}
      BLAGUES_API_TOKEN: ${BLAGUES_API_TOKEN}
      PASTEBIN_API_KEY: ${PASTEBIN_API_KEY}
      ERROR_CHANNEL_ID: ${ERROR_CHANNEL_ID:-}
      DISCORD_ERROR_REPORTER_TEST: ${DISCORD_ERROR_REPORTER_TEST:-false}
      DASHBOARD_URL: ${DASHBOARD_URL:-}
