// Mapping complet des noms de royaumes WoW pour l'API Blizzard
// Basé sur les données officielles de toutes les régions

export const REALM_MAPPING: Record<string, string> = {
    // === SERVEURS EUROPÉENS FRANÇAIS ===
    'kirin tor': 'kirin-tor',
    'kirintor': 'kirin-tor',
    'kirin-tor': 'kirin-tor',
    'hyjal': 'hyjal',
    'dalaran': 'dalaran',
    'elune': 'elune',
    'culte de la rive noire': 'culte-de-la-rive-noire',
    'ysondre': 'ysondre',
    'archimonde': 'archimonde',
    'illidan': 'illidan',
    'confrérie du thorium': 'confrerie-du-thorium',
    'confrerie du thorium': 'confrerie-du-thorium',
    'cho\'gall': 'chogall',
    'chogall': 'chogall',
    'sargeras': 'sargeras',
    'varimathras': 'varimathras',
    'eldre\'thalas': 'eldrethalas',
    'eldrethalas': 'eldrethalas',
    'conseil des ombres': 'conseil-des-ombres',
    'sinstralis': 'sinstralis',
    'rashgarroth': 'rashgarroth',
    'mal\'ganis': 'malganis',
    'malganis': 'malganis',
    'ner\'zhul': 'nerzhul',
    'nerzhul': 'nerzhul',
    'throk\'tar': 'throktar',
    'throktar': 'throktar',
    'drek\'thar': 'drekthar',
    'drekthar': 'drekthar',
    'krasus': 'krasus',
    'medivh': 'medivh',
    'suramar': 'suramar',
    'les clairvoyants': 'les-clairvoyants',
    'les sentinelles': 'les-sentinelles',
    'marécage de zangar': 'marecage-de-zangar',
    'temple noir': 'temple-noir',
    'la croisade écarlate': 'la-croisade-ecarlate',
    'fordragon': 'fordragon',
    'kael\'thas': 'kaelthas',
    'kaelthas': 'kaelthas',
    'garona': 'garona',
    'vol\'jin': 'voljin',
    'voljin': 'voljin',
    
    // === SERVEURS EUROPÉENS ANGLAIS ===
    'tarren mill': 'tarren-mill',
    'tarrenmill': 'tarren-mill',
    'silvermoon': 'silvermoon',
    'outland': 'outland',
    'kazzak': 'kazzak',
    'twisting nether': 'twisting-nether',
    'twistingnether': 'twisting-nether',
    'ragnaros': 'ragnaros',
    'draenor': 'draenor',
    'burning legion': 'burning-legion',
    'burninglegion': 'burning-legion',
    'stormscale': 'stormscale',
    'frostmourne': 'frostmourne',
    'chamber of aspects': 'chamber-of-aspects',
    'sylvanas': 'sylvanas',
    'ravencrest': 'ravencrest',
    'doomhammer': 'doomhammer',
    'defias brotherhood': 'defias-brotherhood',
    'the maelstrom': 'the-maelstrom',
    'earthen ring': 'earthen-ring',
    'shadowsong': 'shadowsong',
    'aszune': 'aszune',
    'auchindoun': 'auchindoun',
    'dunemaul': 'dunemaul',
    'jaedenar': 'jaedenar',
    'bloodhoof': 'bloodhoof',
    'dragonmaw': 'dragonmaw',
    'skullcrusher': 'skullcrusher',
    'spinebreaker': 'spinebreaker',
    'wildhammer': 'wildhammer',
    'thunderhorn': 'thunderhorn',
    'blade\'s edge': 'blades-edge',
    'bladesedge': 'blades-edge',
    'aggramar': 'aggramar',
    'hellscream': 'hellscream',
    'sha\'tar': 'shatar',
    'shatar': 'shatar',
    'trollbane': 'trollbane',
    'chromaggus': 'chromaggus',
    'crushridge': 'crushridge',
    'daggerspine': 'daggerspine',
    'emeriss': 'emeriss',
    'hakkar': 'hakkar',
    'neptulon': 'neptulon',
    'stonemaul': 'stonemaul',
    'terenas': 'terenas',
    'bloodscalp': 'bloodscalp',
    'boulderfist': 'boulderfist',
    'talnivarr': 'talnivarr',
    'laughing skull': 'laughing-skull',
    'laughingskull': 'laughing-skull',
    'magtheridon': 'magtheridon',
    'karazhan': 'karazhan',
    'lightbringer': 'lightbringer',
    'mazrigos': 'mazrigos',
    'vek\'nilash': 'veknilash',
    'veknilash': 'veknilash',
    'bronze dragonflight': 'bronze-dragonflight',
    'nordrassil': 'nordrassil',
    'vashj': 'vashj',
    'quelthalas': 'quelthalas',
    'azjol-nerub': 'azjol-nerub',
    'azjolnerub': 'azjol-nerub',
    'quel\'thalas': 'quelthalas',
    'turalyon': 'turalyon',
    'dun morogh': 'dun-morogh',
    'dunmorogh': 'dun-morogh',
    'zuluhed': 'zuluhed',
    'uldum': 'uldum',
    'grim batol': 'grim-batol',
    'grimbatol': 'grim-batol',
    'aggra-português': 'aggra-portugues',
    'aggra': 'aggra-portugues',
    'goldrinn': 'goldrinn',
    'nemesis': 'nemesis',
    'azshara': 'azshara',
    'gallywix': 'gallywix',
    
    // === SERVEURS EUROPÉENS ALLEMANDS ===
    'antonidas': 'antonidas',
    'blackhand': 'blackhand',
    'blackmoore': 'blackmoore',
    'blackrock': 'blackrock',
    'destromath': 'destromath',
    'dethecus': 'dethecus',
    'die aldor': 'die-aldor',
    'diealdor': 'die-aldor',
    'eredar': 'eredar',
    'frostwolf': 'frostwolf',
    'gilneas': 'gilneas',
    'kel\'thuzad': 'kelthuzad',
    'kelthuzad': 'kelthuzad',
    'kil\'jaeden': 'kiljaeden',
    'kiljaeden': 'kiljaeden',
    'lothar': 'lothar',
    'madmortem': 'madmortem',
    'malfurion': 'malfurion',
    'mannoroth': 'mannoroth',
    'nathrezim': 'nathrezim',
    'nera\'thor': 'nerathor',
    'nerathor': 'nerathor',
    'norgannon': 'norgannon',
    'perenolde': 'perenolde',
    'proudmoore': 'proudmoore',
    'sen\'jin': 'senjin',
    'senjin': 'senjin',
    'thrall': 'thrall',
    'tirion': 'tirion',
    'un\'goro': 'ungoro',
    'ungoro': 'ungoro',
    'area-52': 'area-52',
    'area52': 'area-52',
    'arthas': 'arthas',
    'baelgun': 'baelgun',
    'taerar': 'taerar',
    'terrordar': 'terrordar',
    'theradras': 'theradras',
    'tichondrius': 'tichondrius',
    'uldaman': 'uldaman',
    'wrathbringer': 'wrathbringer',
    'die nachtwache': 'die-nachtwache',
    'dienachtwache': 'die-nachtwache',
    'der rat von dalaran': 'der-rat-von-dalaran',
    'derratvondalaran': 'der-rat-von-dalaran',
    'die silberne hand': 'die-silberne-hand',
    'diesilbernehand': 'die-silberne-hand',
    'zirkel des cenarius': 'zirkel-des-cenarius',
    'zirkeldescentarius': 'zirkel-des-cenarius',
    'der abyssische rat': 'der-abyssische-rat',
    'derabyssischerat': 'der-abyssische-rat',
    'das syndikat': 'das-syndikat',
    'dassyndikat': 'das-syndikat',
    'die todeskrallen': 'die-todeskrallen',
    'dietodeskrallen': 'die-todeskrallen',
    'alexstrasza': 'alexstrasza',
    'alleria': 'alleria',
    'ambossar': 'ambossar',
    'aman\'thul': 'amanthul',
    'amanthul': 'amanthul',
    'anetheron': 'anetheron',
    'anub\'arak': 'anubarak',
    'anubarak': 'anubarak',
    'arygos': 'arygos',
    'azuremyst': 'azuremyst',
    'balnazzar': 'balnazzar',
    'blackscar': 'blackscar',
    'blutkessel': 'blutkessel',
    'durotan': 'durotan',
    'echsenkessel': 'echsenkessel',
    'garrosh': 'garrosh',
    'gorgonnash': 'gorgonnash',
    'gul\'dan': 'guldan',
    'guldan': 'guldan',
    'kargath': 'kargath',
    'khaz modan': 'khaz-modan',
    'khazmodan': 'khaz-modan',
    'khaz\'goroth': 'khazgoroth',
    'khazgoroth': 'khazgoroth',
    'krag\'jin': 'kragjin',
    'kragjin': 'kragjin',
    'nozdormu': 'nozdormu',
    'onyxia': 'onyxia',
    'rajaxx': 'rajaxx',
    'rexxar': 'rexxar',
    'shattered halls': 'shattered-halls',
    'shatteredhalls': 'shattered-halls',
    'shattered hand': 'shattered-hand',
    'shatteredhand': 'shattered-hand',
    'vek\'lor': 'veklor',
    'veklor': 'veklor',
    'venoxis': 'venoxis',
    'volcanus': 'volcanus',
    'wellspring': 'wellspring',
    'zenedar': 'zenedar',
    
    // === SERVEURS EUROPÉENS AUTRES LANGUES ===
    
    // Italien
    'pozzo dell\'eternità': 'pozzo-delleternita',
    'pozzodelleternita': 'pozzo-delleternita',
    
    // Espagnol
    'cólmillo torcido': 'colmillo-torcido',
    'colmillotorcido': 'colmillo-torcido',
    'tyrande': 'tyrande',
    'dun modr': 'dun-modr',
    'dunmodr': 'dun-modr',
    'minahonda': 'minahonda',
    'los errantes': 'los-errantes',
    'loserrantes': 'los-errantes',
    'shen\'dralar': 'shendralar',
    'shendralar': 'shendralar',
    'zul\'jin': 'zuljin',
    'zuljin': 'zuljin',
    'exodar': 'exodar',
    'c\'thun': 'cthun',
    'cthun': 'cthun',
    
    // Russe
    'галакронд': 'galakrond',
    'galakrond': 'galakrond',
    'гордунни': 'gordunni',
    'gordunni': 'gordunni',
    'гром': 'grom',
    'grom': 'grom',
    'пиратская бухта': 'piratskaya-bukhta',
    'piratskayabukhta': 'piratskaya-bukhta',
    'свежеватель душ': 'svezhevatel-dush',
    'ревущий фьорд': 'revushchiy-ford',
    'revushchiyford': 'revushchiy-ford',
    'страж смерти': 'strazh-smerti',
    'strazhsmerti': 'strazh-smerti',
    'ashenvale': 'ashenvale',
    'booty bay': 'booty-bay',
    'bootybay': 'booty-bay',
    'howling fjord': 'howling-fjord',
    'howlingfjord': 'howling-fjord',
    'soulflayer': 'soulflayer',
    'borean tundra': 'borean-tundra',
    'boreantundra': 'borean-tundra',
    'thermaplugg': 'thermaplugg',
    'черный шрам': 'chernyy-shram',
    'chernyyshram': 'chernyy-shram',
    'седогрив': 'sedogriv',
    'sedogriv': 'sedogriv',
    'разувий': 'razuviy',
    'razuviy': 'razuviy',
    
    // === SERVEURS AMÉRICAINS ===
    'stormrage': 'stormrage',
    'bleeding hollow': 'bleeding-hollow',
    'bleedinghollow': 'bleeding-hollow',
    'darkspear': 'darkspear',
    'deathwing': 'deathwing',
    'emerald dream': 'emerald-dream',
    'emeralddream': 'emerald-dream',
    'shadow council': 'shadow-council',
    'shadowcouncil': 'shadow-council',
    'burning blade': 'burning-blade',
    'burningblade': 'burning-blade',
    'lightning\'s blade': 'lightnings-blade',
    'lightningsblade': 'lightnings-blade',
    'aegwynn': 'aegwynn',
    'akama': 'akama',
    'altar of storms': 'altar-of-storms',
    'altarofstorms': 'altar-of-storms',
    'andorhal': 'andorhal',
    'anvilmar': 'anvilmar',
    'arathor': 'arathor',
    'argent dawn': 'argent-dawn',
    'argentdawn': 'argent-dawn',
    'azgalor': 'azgalor',
    'azralon': 'azralon',
    'black dragonflight': 'black-dragonflight',
    'blackdragonflight': 'black-dragonflight',
    'blackwater raiders': 'blackwater-raiders',
    'blackwaterraiders': 'blackwater-raiders',
    'bladefist': 'bladefist',
    'bonechewer': 'bonechewer',
    'bronzebeard': 'bronzebeard',
    'caelestrasz': 'caelestrasz',
    'cairne': 'cairne',
    'cenarion circle': 'cenarion-circle',
    'cenarioncircle': 'cenarion-circle',
    'cenarius': 'cenarius',
    'coilfang': 'coilfang',
    'dath\'remar': 'dathremar',
    'dathremar': 'dathremar',
    'dawnbringer': 'dawnbringer',
    'demon soul': 'demon-soul',
    'demonsoul': 'demon-soul',
    'dentarg': 'dentarg',
    'detheroc': 'detheroc',
    'dragonblight': 'dragonblight',
    'drak\'tharon': 'draktharon',
    'draktharon': 'draktharon',
    'drak\'thul': 'drakthul',
    'drakthul': 'drakthul',
    'draka': 'draka',
    'drenden': 'drenden',
    'duskwood': 'duskwood',
    'echo isles': 'echo-isles',
    'echoisles': 'echo-isles',
    'eitrigg': 'eitrigg',
    'eonar': 'eonar',
    'executus': 'executus',
    'farstriders': 'farstriders',
    'feathermoon': 'feathermoon',
    'fenris': 'fenris',
    'firetree': 'firetree',
    'fizzcrank': 'fizzcrank',
    'frostmane': 'frostmane',
    'garithos': 'garithos',
    'ghostlands': 'ghostlands',
    'gnomeregan': 'gnomeregan',
    'gorefiend': 'gorefiend',
    'greymane': 'greymane',
    'grizzly hills': 'grizzly-hills',
    'grizzlyhills': 'grizzly-hills',
    'gurubashi': 'gurubashi',
    'haomarush': 'haomarush',
    'hydraxis': 'hydraxis',
    'icecrown': 'icecrown',
    'jubei\'thos': 'jubeithos',
    'jubeithos': 'jubeithos',
    'kalecgos': 'kalecgos',
    'khadgar': 'khadgar',
    'kilrogg': 'kilrogg',
    'kirin tor': 'kirin-tor',
    'kirintor': 'kirin-tor',
    'korgath': 'korgath',
    'korialstrasz': 'korialstrasz',
    'kul tiras': 'kul-tiras',
    'kultiras': 'kul-tiras',
    'lethon': 'lethon',
    'lightninghoof': 'lightninghoof',
    'llane': 'llane',
    'madoran': 'madoran',
    'maelstrom': 'maelstrom',
    'maiev': 'maiev',
    'malorne': 'malorne',
    'malygos': 'malygos',
    'misha': 'misha',
    'mok\'nathal': 'moknathal',
    'moknathal': 'moknathal',
    'moon guard': 'moon-guard',
    'moonguard': 'moon-guard',
    'moonrunner': 'moonrunner',
    'mug\'thol': 'mugthol',
    'mugthol': 'mugthol',
    'muradin': 'muradin',
    'nagrand': 'nagrand',
    'nazgrel': 'nazgrel',
    'nazjatar': 'nazjatar',
    'nesingwary': 'nesingwary',
    'phlegethon': 'phlegethon',
    'quel\'dorei': 'queldorei',
    'queldorei': 'queldorei',
    'ravenholdt': 'ravenholdt',
    'rivendare': 'rivendare',
    'runetotem': 'runetotem',
    'saurfang': 'saurfang',
    'scarlet crusade': 'scarlet-crusade',
    'scarletcrusade': 'scarlet-crusade',
    'scilla': 'scilla',
    'sentinels': 'sentinels',
    'shadowmoon': 'shadowmoon',
    'shandris': 'shandris',
    'shu\'halo': 'shuhalo',
    'shuhalo': 'shuhalo',
    'silver hand': 'silver-hand',
    'silverhand': 'silver-hand',
    'sisters of elune': 'sisters-of-elune',
    'sistersofelune': 'sisters-of-elune',
    'skywall': 'skywall',
    'smolderthorn': 'smolderthorn',
    'spirestone': 'spirestone',
    'staghelm': 'staghelm',
    'steamwheedle cartel': 'steamwheedle-cartel',
    'steamwheedlecartel': 'steamwheedle-cartel',
    'stormreaver': 'stormreaver',
    'tanaris': 'tanaris',
    'terokkar': 'terokkar',
    'thaurissan': 'thaurissan',
    'the forgotten coast': 'the-forgotten-coast',
    'theforgottencoast': 'the-forgotten-coast',
    'the scryers': 'the-scryers',
    'thescryers': 'the-scryers',
    'the underbog': 'the-underbog',
    'theunderbog': 'the-underbog',
    'the venture co': 'the-venture-co',
    'theventureco': 'the-venture-co',
    'thorium brotherhood': 'thorium-brotherhood',
    'thoriumbrotherhood': 'thorium-brotherhood',
    'thunderlord': 'thunderlord',
    'tol barad': 'tol-barad',
    'tolbarad': 'tol-barad',
    'tortheldrin': 'tortheldrin',
    'undermine': 'undermine',
    'ursin': 'ursin',
    'uther': 'uther',
    'velen': 'velen',
    'warsong': 'warsong',
    'whisperwind': 'whisperwind',
    'windrunner': 'windrunner',
    'winterhoof': 'winterhoof',
    'wyrmrest accord': 'wyrmrest-accord',
    'wyrmrestaccord': 'wyrmrest-accord',
    'ysera': 'ysera',
    'zangarmarsh': 'zangarmarsh',
    
    // Océanie
    'barthilas': 'barthilas',
    'dreadmaul': 'dreadmaul',
    'gundrak': 'gundrak',
    
    // === SERVEURS CORÉENS ===
    // (Utilisant les mêmes noms que leurs équivalents d'autres régions)
    
    // === SERVEURS TAÏWANAIS ===
    'crystalpine stinger': 'crystalpine-stinger',
    'crystalpinestinger': 'crystalpine-stinger',
    'demon fall canyon': 'demon-fall-canyon',
    'demonfallcanyon': 'demon-fall-canyon',
    'light\'s hope': 'lights-hope',
    'lightshope': 'lights-hope',
    'menethil': 'menethil',
    'order of the cloud serpent': 'order-of-the-cloud-serpent',
    'orderofthecloudserpent': 'order-of-the-cloud-serpent',
    'silverwing hold': 'silverwing-hold',
    'silverwinghold': 'silverwing-hold',
    'sundown marsh': 'sundown-marsh',
    'sundownmarsh': 'sundown-marsh',
    'world tree': 'world-tree',
    'worldtree': 'world-tree',
    'zealotry': 'zealotry'
};

// Fonction pour normalizer un nom de royaume
export function normalizeRealmName(realmName: string): string {
    const normalized = realmName.toLowerCase().trim();
    return REALM_MAPPING[normalized] || normalized.replace(/['\s]/g, '-').replace(/[^a-z0-9-]/g, '');
}
